### ISSUE TITLE
没有linux版本吗？

### ISSUE THREAD

**Issue by shayulei** [gylang/aliyundriver-webdav-software-ui#1]
最好是有linux版，复杂得话就做成docker

**Comment by gylang** [comment]
没有liunx版,如果你想用linux的,你可以直接使用rust的[[aliyundriver-webdav](https://github.com/gylang/aliyundriver-webdav-software-ui)](https://github.com/messense/aliyundrive-webdav)

**Comment by gylang** [comment]
没有liunx版,如果你想用linux的,你可以直接使用rust的[[aliyundriver-webdav](https://github.com/gylang/aliyundriver-webdav-software-ui)](https://github.com/messense/aliyundrive-webdav)
