### ISSUE TITLE
设置开机启动后没有运行webdav

### ISSUE THREAD

**Issue by jojo552** [gylang/aliyundriver-webdav-software-ui#2]
开机启动设置成功了，但是webdav没有自动运行，还是需要手动打开软件启动webdav

**Comment by 1oneisall** [comment]
> 开机启动设置成功了，但是webdav没有自动运行，还是需要手动打开软件启动webdav

我遇到的问题是，需要先打开软件停止后，再重新启动，Raidrive 才连接得到。

**Comment by gylang** [comment]
可以看一下log日志,看一下你是啥问题

**Comment by 1oneisall** [comment]
> 可以看一下log日志,看一下你是啥问题

重启电脑后，没有生成 2022-XX-XX-webdav-executor.log，但 UI 是显示启动的。
需要手动停止再启动。

**Comment by gylang** [comment]
你是不是移动了程序路径或者放到c盘之类的
