### ISSUE TITLE
请问windows直接下载哪个版本的zip？谢谢！

### ISSUE THREAD

**Issue by jijie94** [gylang/aliyundriver-webdav-software-ui#4]

**Comment by gylang** [comment]
[aliyundrive-webdav-v1.5.0.x86_64-pc-windows-msvc.zip](https://github.com/messense/aliyundrive-webdav/releases/download/v1.5.0/aliyundrive-webdav-v1.5.0.x86_64-pc-windows-msvc.zip)

**Comment by jijie94** [comment]
> [aliyundrive-webdav-v1.5.0.x86_64-pc-windows-msvc.zip](https://github.com/messense/aliyundrive-webdav/releases/download/v1.5.0/aliyundrive-webdav-v1.5.0.x86_64-pc-windows-msvc.zip)

谢谢

**Comment by jijie94** [comment]
谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月6日(星期一) 晚上10:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [gylang/aliyundriver-webdav-software-ui] 请问windows直接下载哪个版本的zip？谢谢！ (Issue #4)





 
aliyundrive-webdav-v1.5.0.x86_64-pc-windows-msvc.zip
