### ISSUE TITLE
大佬 打开软件能不能自动触发启动啊

### ISSUE THREAD

**Issue by clairvoyant1218** [gylang/aliyundriver-webdav-software-ui#8]
现在权限都给了 自启还是有点问题  我打算快捷方式加到启动项目单   但应该完善一下 webdav启动优先raidrive  打开软件自动触发webdav启动
这个软件有图形化界面 最小白向了   大有前途   做成付费软件 我也愿意买

**Comment by gylang** [comment]
付费就算了吧, 我只是写个壳子而已, 应该是webdav重试的时候,还没连上webdav的服务,新版加了重试次数, 你看看能不能解决

**Comment by clairvoyant1218** [comment]
> 

比尔盖茨也就做了个图形化界面而已 没人做你第一个做 这就足够有商业价值了
